version: '3.6'
services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/app
#      - .:/usr/app
#      - /usr/app/node_modules
    links:
      - "redis"
        #command: "npm run start-server"
    command: "npm start"
    environment:
      - REDIS_HOST='redis'
  redis:
#    build: ./redis
    image: "redis:alpine"
    expose:
      - "6379"
    volumes:
      - ./data:/data/
#    restart: always
    privileged: true
    sysctls:
      net.core.somaxconn: '511'
    entrypoint: 'redis-server --appendonly yes'

# TODO  https://github.com/wurstmeister/kafka-docker
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
#      KAFKA_CREATE_TOPICS: "test:1:1"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
##    command: 'chown -R 999:999 /data/redis'
##    volumes:
##volumes:
##  data:
